version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_IP: 'mongo'
      DB_NAME: 'PhishingDB'
      DB_PORT: '27017'
      EMAIL_API: 'http://localhost:5058/api/email'
      JWT_TOKEN: 'AMIRASDASDAS'
      ALLOWED_ORIGINS: 'http://localhost:8080,http://localhost:3000,http://localhost:5173'
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: